// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomePageDocumentDataSlicesSlice = HighlightedHeroWithStatisticsSlice;

/**
 * Content for Strona Główna documents
 */
interface HomePageDocumentData {
  /**
   * Tytuł field in *Strona Główna*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Szkoła Tańca Chill
   * - **API ID Path**: HomePage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Strona Główna*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: HomePage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Strona Główna*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: HomePage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Strona Główna*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: HomePage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Strona Główna*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: HomePage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Strona Główna document from Prismic
 *
 * - **API ID**: `HomePage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "HomePage",
    Lang
  >;

type PageDocumentDataSlicesSlice = RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = HomePageDocument | PageDocument;

/**
 * Item in *HighlightedHeroWithStatistics → Default → Primary → Statistics*
 */
export interface HighlightedHeroWithStatisticsSliceDefaultPrimaryStatisticsItem {
  /**
   * Stat Number field in *HighlightedHeroWithStatistics → Default → Primary → Statistics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlighted_hero_with_statistics.default.primary.statistics[].stat_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  stat_number: prismic.KeyTextField;

  /**
   * Stat Label field in *HighlightedHeroWithStatistics → Default → Primary → Statistics*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlighted_hero_with_statistics.default.primary.statistics[].stat_label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  stat_label: prismic.RichTextField;
}

/**
 * Primary content in *HighlightedHeroWithStatistics → Default → Primary*
 */
export interface HighlightedHeroWithStatisticsSliceDefaultPrimary {
  /**
   * Main Title field in *HighlightedHeroWithStatistics → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: highlighted_hero_with_statistics.default.primary.main_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_title: prismic.TitleField;

  /**
   * Description field in *HighlightedHeroWithStatistics → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlighted_hero_with_statistics.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button field in *HighlightedHeroWithStatistics → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Poznaj Nas
   * - **API ID Path**: highlighted_hero_with_statistics.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button: prismic.KeyTextField;

  /**
   * Image field in *HighlightedHeroWithStatistics → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: highlighted_hero_with_statistics.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Statistics field in *HighlightedHeroWithStatistics → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: highlighted_hero_with_statistics.default.primary.statistics[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  statistics: prismic.GroupField<
    Simplify<HighlightedHeroWithStatisticsSliceDefaultPrimaryStatisticsItem>
  >;
}

/**
 * Default variation for HighlightedHeroWithStatistics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with main title, description, image and statistics.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightedHeroWithStatisticsSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<HighlightedHeroWithStatisticsSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *HighlightedHeroWithStatistics*
 */
type HighlightedHeroWithStatisticsSliceVariation =
  HighlightedHeroWithStatisticsSliceDefault;

/**
 * HighlightedHeroWithStatistics Shared Slice
 *
 * - **API ID**: `highlighted_hero_with_statistics`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightedHeroWithStatisticsSlice = prismic.SharedSlice<
  "highlighted_hero_with_statistics",
  HighlightedHeroWithStatisticsSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HighlightedHeroWithStatisticsSlice,
      HighlightedHeroWithStatisticsSliceDefaultPrimaryStatisticsItem,
      HighlightedHeroWithStatisticsSliceDefaultPrimary,
      HighlightedHeroWithStatisticsSliceVariation,
      HighlightedHeroWithStatisticsSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
