// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  highlighted_hero_with_statistics: dynamic(
    () => import("./HighlightedHeroWithStatistics"),
  ),
  media_gallery: dynamic(() => import("./MediaGallery")),
  rich_text: dynamic(() => import("./RichText")),
  services_grid: dynamic(() => import("./ServicesGrid")),
};
