// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_map_form: dynamic(() => import("./ContactForm")),
  content_image_split: dynamic(() => import("./ContentImageSplit")),
  highlighted_hero_with_statistics: dynamic(() => import("./Hero")),
  image_collage: dynamic(() => import("./ImageCollage")),
  media_gallery: dynamic(() => import("./MediaGallery")),
  schedule_grid: dynamic(() => import("./ScheduleGrid")),
  services_grid: dynamic(() => import("./ServicesGrid")),
  side_by_side_image_text: dynamic(() => import("./SideBySideImageText")),
  steps_with_intro: dynamic(() => import("./StepsWithIntro")),
};
